]q (]q(cnumpy.core.multiarray
scalar
qcnumpy
dtype
qX   i4qK K뇉Rq(KX   <qNNNJJK tqbC   q	냧
RqhhC
   q냧
RqhhC   q냧Rqe]q(hhC+   q냧RqhhC
   q냧RqhhC   q냧Rqe]q(hhCJ   q냧RqhhC
   q 냧!Rq"hhC   q#냧$Rq%e]q&(hhCj   q'냧(Rq)hhC
   q*냧+Rq,hhC   q-냧.Rq/e]q0(hhC?  q1냧2Rq3hhC
   q4냧5Rq6hhC   q7냧8Rq9e]q:(hhC?  q;냧<Rq=hhC
   q>냧?Rq@hhC   qA냧BRqCe]qD(hhC?  qE냧FRqGhhC
   qH냧IRqJhhC   qK냧LRqMe]qN(hhC?  qO냧PRqQhhC
   qR냧SRqThhC   qU냧VRqWe]qX(hhC	  qY냧ZRq[hhC
   q\냧]Rq^hhC   q_냧`Rqae]qb(hhC)  qc냧dRqehhC
   qf냧gRqhhhC   qi냧jRqke]ql(hhCI  qm냧nRqohhC
   qp냧qRqrhhC   qs냧tRque]qv(hhCi  qw냧xRqyhhC
   qz냧{Rq|hhC   q}냧~Rqe]q(hhC?  q걝q괨q긤hC
   q꼩q꿘q냜hC   q뇛q늃q뎓]q?hhC?  q땰q똓q뛥hC
   q럣q뢗q릈hC   q몘q뭃q밻]q?hhC?  q븚q뻉q뾥hC
   q쁿q셊q쉎hC   q썓q쏳q쓊]q?hhC   q웺q쟓q죋hC%   q쥍q즄q쨑hC   q쪌q쪹q쬮]q?hhC+   q찂q챂q쳂hC%   q쵄q쵷q췪hC   q칳q캲q켩]q?hhCJ   q퀐q큃q킾hC%   q텉q톀q퇲hC   q퉮q튣q팫]q?hhCj   q퐜q푋q퓀hC%   q픿q핾q헺hC   q횈q훀q휿]q?hhC?  q?q?q?hC%   q?q?q?hC   q?q?q?]q?hhC?  q?q?q?hC%   q?q?q?hC   q?q?q?]q?hhC?  q?q?q?hC%   q?q?q?hC   q?q?q?]q?hhC?  q?q?q?hC%   q?q?q?hC   q?q?q?]q?hhC	  q?q?q?hC%   q?q?q?hC   q?q?q?]q?hhC)  q?q?q?hC%   q?q?q?hC   q냨   Rr  e]r  (hhCI  r  냨  Rr  hhC%   r  냨  Rr  hhC   r	  냨
  Rr  e]r  (hhCi  r
  냨  Rr  hhC%   r  냨  Rr  hhC   r  냨  Rr  e]r  (hhC?  r  냨  Rr  hhC%   r  냨  Rr  hhC   r  냨  Rr  e]r   (hhC?  r!  냨"  Rr#  hhC%   r$  냨%  Rr&  hhC   r'  냨(  Rr)  e]r*  (hhC?  r+  냨,  Rr-  hhC%   r.  냨/  Rr0  hhC   r1  냨2  Rr3  e]r4  (hhC   r5  냨6  Rr7  hhC=   r8  냨9  Rr:  hhC   r;  냨<  Rr=  e]r>  (hhC+   r?  냨@  RrA  hhC=   rB  냨C  RrD  hhC   rE  냨F  RrG  e]rH  (hhCJ   rI  냨J  RrK  hhC=   rL  냨M  RrN  hhC   rO  냨P  RrQ  e]rR  (hhCj   rS  냨T  RrU  hhC=   rV  냨W  RrX  hhC   rY  냨Z  Rr[  e]r\  (hhC?  r]  냨^  Rr_  hhC=   r`  냨a  Rrb  hhC   rc  냨d  Rre  e]rf  (hhC?  rg  냨h  Rri  hhC=   rj  냨k  Rrl  hhC   rm  냨n  Rro  e]rp  (hhC?  rq  냨r  Rrs  hhC=   rt  냨u  Rrv  hhC   rw  냨x  Rry  e]rz  (hhC?  r{  냨|  Rr}  hhC=   r~  냨  Rr  hhC   r?  냨?  Rr?  e]r?  (hhC	  r?  냨?  Rr?  hhC=   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC)  r?  냨?  Rr?  hhC=   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCI  r?  냨?  Rr?  hhC=   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCi  r?  냨?  Rr?  hhC=   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC=   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC=   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC=   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC   r?  냨?  Rr?  hhCT   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC+   r?  냨?  Rr?  hhCT   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCJ   r?  냨?  Rr?  hhCT   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCj   r?  냨?  Rr?  hhCT   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCT   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr  hhCT   r   냨  Rr  hhC   r  냨  Rr  e]r  (hhC?  r  냨  Rr	  hhCT   r
  냨  Rr  hhC   r
  냨  Rr  e]r  (hhC?  r  냨  Rr  hhCT   r  냨  Rr  hhC   r  냨  Rr  e]r  (hhC	  r  냨  Rr  hhCT   r  냨  Rr   hhC   r!  냨"  Rr#  e]r$  (hhC)  r%  냨&  Rr'  hhCT   r(  냨)  Rr*  hhC   r+  냨,  Rr-  e]r.  (hhCI  r/  냨0  Rr1  hhCT   r2  냨3  Rr4  hhC   r5  냨6  Rr7  e]r8  (hhCi  r9  냨:  Rr;  hhCT   r<  냨=  Rr>  hhC   r?  냨@  RrA  e]rB  (hhC?  rC  냨D  RrE  hhCT   rF  냨G  RrH  hhC   rI  냨J  RrK  e]rL  (hhC?  rM  냨N  RrO  hhCT   rP  냨Q  RrR  hhC   rS  냨T  RrU  e]rV  (hhC?  rW  냨X  RrY  hhCT   rZ  냨[  Rr\  hhC   r]  냨^  Rr_  e]r`  (hhC   ra  냨b  Rrc  hhCl   rd  냨e  Rrf  hhC   rg  냨h  Rri  e]rj  (hhC+   rk  냨l  Rrm  hhCl   rn  냨o  Rrp  hhC   rq  냨r  Rrs  e]rt  (hhCJ   ru  냨v  Rrw  hhCl   rx  냨y  Rrz  hhC   r{  냨|  Rr}  e]r~  (hhCj   r  냨  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC	  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC)  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCI  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCi  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhCl   r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC   r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr  e]r   (hhC+   r  냨  Rr  hhC?  r  냨  Rr  hhC   r  냨  Rr	  e]r
  (hhCJ   r  냨  Rr
  hhC?  r  냨  Rr  hhC   r  냨  Rr  e]r  (hhCj   r  냨  Rr  hhC?  r  냨  Rr  hhC   r  냨  Rr  e]r  (hhC?  r  냨   Rr!  hhC?  r"  냨#  Rr$  hhC   r%  냨&  Rr'  e]r(  (hhC?  r)  냨*  Rr+  hhC?  r,  냨-  Rr.  hhC   r/  냨0  Rr1  e]r2  (hhC?  r3  냨4  Rr5  hhC?  r6  냨7  Rr8  hhC   r9  냨:  Rr;  e]r<  (hhC?  r=  냨>  Rr?  hhC?  r@  냨A  RrB  hhC   rC  냨D  RrE  e]rF  (hhC	  rG  냨H  RrI  hhC?  rJ  냨K  RrL  hhC   rM  냨N  RrO  e]rP  (hhC)  rQ  냨R  RrS  hhC?  rT  냨U  RrV  hhC   rW  냨X  RrY  e]rZ  (hhCI  r[  냨\  Rr]  hhC?  r^  냨_  Rr`  hhC   ra  냨b  Rrc  e]rd  (hhCi  re  냨f  Rrg  hhC?  rh  냨i  Rrj  hhC   rk  냨l  Rrm  e]rn  (hhC?  ro  냨p  Rrq  hhC?  rr  냨s  Rrt  hhC   ru  냨v  Rrw  e]rx  (hhC?  ry  냨z  Rr{  hhC?  r|  냨}  Rr~  hhC   r  냨  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC   r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC+   r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCJ   r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCj   r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC?  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC	  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhC)  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCI  r?  냨?  Rr?  hhC?  r?  냨?  Rr?  hhC   r?  냨?  Rr?  e]r?  (hhCi  r?  냨?  Rr?  hhC?  r?  냨  Rr   hhC   r  냨  Rr  e]r  (hhC?  r  냨  Rr  hhC?  r  냨	  Rr
  hhC   r  냨  Rr
  e]r  (hhC?  r  냨  Rr  hhC?  r  냨  Rr  hhC   r  냨  Rr  e]r  (hhC?  r  냨  Rr  hhC?  r  냨  Rr  hhC   r  냨   Rr!  ee.
